In [1]:
!pip install pandas
!pip install numpy
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\anaconda\lib\site-packages (2.3.5)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\anaconda\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\anaconda\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\anaconda\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\anaconda\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\anaconda\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\anaconda\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\anaconda\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\anaconda\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\anaconda\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\anaconda\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [4]:
#Baixei as bibliotecas necessárias
#Lê e acessa arquivos
import pandas as pd
#Faz e facilita operações matemáticas
import numpy as np
#Auxilia com a criação de gráficos
import matplotlib.pyplot as plt

dataset = pd.read_excel(r"C:\Users\henrique_dahmer\Downloads\producao_motores_weg_iot_10000.xlsx")
display(dataset)

,DATA_HORA,SETOR,MAQUINA,COD_MOTOR,SENSOR,TEMP_ESTATOR,VIBRACAO_MM,CORRENTE_A,TENSAO_V,PRESSAO_BAR,UMIDADE_%,STATUS_FINAL,COD_FALHA,OPERADOR,TURNO,CONSUMO_KWH
0,2026-01-01 00:00:00,Teste,MQ-001,MT-0000001,IOT-0037,81.4,7.73,31.06,211.6,5.76,38.5,OK,---,CARLOS SOUZA,Terceiro,287.61
1,2026-01-01 00:15:00,Bobinagem,MQ-006,MT-0000001,IOT-0014,70.5,4.73,25.22,239.3,5.78,38.9,REPROVADO,F099,Bruno Rocha,3,269.35
2,2026-01-01 00:30:00,Bobinagem,MQ-010,MT-0000001,IOT-0066,53.9,3.87,11.89,229.9,9.85,63.9,REPROVADO,---,ANA LIMA,Terceiro,157.84
3,2026-01-01 00:45:00,Usinagem,MQ-029,MT-0000001,IOT-0014,47.7,10.05,32.72,217.8,9.47,72.1,Aprovado,E203,MARCOS DIAS,3,272.03
4,2026-01-01 01:00:00,Bobinagem,MQ-005,MT-0000001,IOT-0045,84.3,10.71,30.93,213.7,5.23,74.3,Ok,---,RICARDO SILVA,Terceiro,87.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2026-04-15 02:45:00,Bobinagem,MQ-023,MT-0009996,IOT-0032,50.8,1.99,24.93,211.5,6.95,43.1,ok,---,Bruno Rocha,Primeiro,134.34
9996,2026-04-15 03:00:00,Teste,MQ-020,MT-0009997,IOT-0032,79.9,1.03,16.15,221.3,3.20,67.9,REPROVADO,---,ANA LIMA,Madrugada,240.65
9997,2026-04-15 03:15:00,Pintura,MQ-022,MT-0009998,IOT-0071,51.6,7.53,15.78,220.3,3.06,46.6,FALHA,---,Lucas Almeida,3,184.12
9998,2026-04-15 03:30:00,Usinagem,MQ-004,MT-0009999,IOT-0029,80.8,3.76,12.66,238.4,3.92,43.0,OK,E305,Ana Lima,Terceiro,190.75
9999,2026-04-15 03:45:00,Pintura,MQ-029,MT-0010000,IOT-0052,67.3,8.38,34.45,218.2,4.68,67.3,FALHA,F012,Ricardo Silva,Segundo,282.43

In [62]:
#Renomeia as colunas para o padrão de utilização da WEG
dataset.columns = ['data_hora', 'setor', 'maquina', 'cod_motor', 'sensor', 'temperatura', 'vibracao', 'corrente', 'tensao', 'pressao', 'umidade', 'status', 'cod_falha', 'operador', 'turno', 'consumo_kwh']

#Exibe a mudança executada
dataset.head()

,data_hora,setor,maquina,cod_motor,sensor,temperatura,vibracao,corrente,tensao,pressao,umidade,status,cod_falha,operador,turno,consumo_kwh
0,2026-01-01 00:00:00,Teste,MQ-001,MT-0000001,IOT-0037,81.4,7.73,31.06,211.6,5.76,38.5,Aprovado,SEM_FALHA,Carlos Souza,3º Turno,287.61
400,2026-01-05 04:00:00,Usinagem,MQ-015,MT-0000401,IOT-0035,69.3,3.57,36.52,234.3,7.17,55.2,Aprovado,SEM_FALHA,João Pereira,1º Turno,225.54
401,2026-01-05 04:15:00,Bobinagem,MQ-004,MT-0000402,IOT-0029,65.2,1.71,9.87,236.5,4.01,40.2,Aprovado,E101,Ricardo Silva,3º Turno,247.07
402,2026-01-05 04:30:00,Pintura,MQ-002,MT-0000403,IOT-0019,51.7,3.12,34.23,211.7,5.39,53.5,Aprovado,E101,Camila Nunes,3º Turno,134.44
403,2026-01-05 04:45:00,Usinagem,MQ-024,MT-0000404,IOT-0018,45.7,8.57,32.04,229.8,6.85,71.6,Aprovado,F012,Lucas Almeida,2º Turno,208.52

In [12]:
dataset.describe()

,data_hora,temperatura,vibração,corrente,tensao,pressao,umidade,consumo_kwh
count,10000,9715.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,2026-02-22 01:52:30,82.727648,7.369376,26.448126,223.86464,6.822846,55.035920,208.866295
min,2026-01-01 00:00:00,-20.000000,-7.920000,0.000000,100.00000,3.000000,35.000000,80.000000
25%,2026-01-27 00:56:15,54.900000,3.750000,17.300000,217.00000,4.770000,45.175000,140.515000
50%,2026-02-22 01:52:30,65.200000,6.580000,26.760000,224.60000,6.600000,55.100000,201.195000
75%,2026-03-20 02:48:45,75.500000,9.370000,35.782500,232.10000,8.360000,65.000000,262.077500
max,2026-04-15 03:45:00,999.000000,79.970000,44.990000,240.00000,29.850000,75.000000,899.840000
std,NaN,130.812782,7.716723,10.868974,12.66341,3.057486,11.476376,98.475409

In [20]:
#quantidade de valores nulos
dataset.isna().sum().sum()

np.int64(2245)

In [19]:
#quantidade de registros duplicados
dataset.duplicated().sum()

np.int64(0)

In [18]:
#quantidade de códigos de falha
dataset['cod_falha'].value_counts(dropna = False)

cod_falha
NaN          1960
E410         1078
SEM_FALHA    1043
E101         1033
F012          984
E305          980
E203          979
F099          976
---           967
Name: count, dtype: int64

In [21]:
#distribuição por setor
dataset['setor'].value_counts()

setor
Bobinagem    1706
Pintura      1699
Montagem     1683
Teste        1672
Expedição    1633
Usinagem     1607
Name: count, dtype: int64

In [22]:
#distribuição por turno
dataset['turno'].value_counts()

turno
Segundo      1504
Madrugada    1449
Primeiro     1431
3            1422
2            1411
Terceiro     1394
1            1389
Name: count, dtype: int64

In [23]:
#distribuição por status
dataset['status'].value_counts()

status
OK           1046
Falha        1037
aprovado     1030
REPROVADO    1026
APROVADO     1015
ok           1004
Reprovado     972
Aprovado      965
FALHA         956
Ok            949
Name: count, dtype: int64

In [31]:
#Motor
#remover espaços
dataset['cod_motor'] = dataset['cod_motor'].str.strip()

#converter para letras maiúsculas
dataset['cod_motor'] = dataset['cod_motor'].str.upper()

#eliminar registros duplicados
dataset = dataset.drop_duplicates(subset=['cod_motor'], keep='first')

#Resultado:
dataset.head()

,data_hora,setor,maquina,cod_motor,sensor,temperatura,vibração,corrente,tensao,pressao,umidade,status,cod_falha,operador,turno,consumo_kwh
0,2026-01-01 00:00:00,Teste,MQ-001,MT-0000001,IOT-0037,81.4,7.73,31.06,211.6,5.76,38.5,OK,---,CARLOS SOUZA,Terceiro,287.61
400,2026-01-05 04:00:00,Usinagem,MQ-015,MT-0000401,IOT-0035,69.3,3.57,36.52,234.3,7.17,55.2,aprovado,NaN,João Pereira,Primeiro,225.54
401,2026-01-05 04:15:00,Bobinagem,MQ-004,MT-0000402,IOT-0029,NaN,1.71,9.87,236.5,4.01,40.2,aprovado,E101,Ricardo Silva,Madrugada,247.07
402,2026-01-05 04:30:00,Pintura,MQ-002,MT-0000403,IOT-0019,51.7,3.12,34.23,211.7,5.39,53.5,ok,E101,Camila Nunes,3,134.44
403,2026-01-05 04:45:00,Usinagem,MQ-024,MT-0000404,IOT-0018,45.7,8.57,32.04,229.8,6.85,71.6,aprovado,F012,Lucas Almeida,Segundo,208.52

In [32]:
#Operadores
#primeira letra maiúscula
dataset['operador'] = dataset['operador'].str.title()

#remoção de espaços extras
dataset['operador'] = dataset['operador'].str.strip()

#Resultado: 
dataset.head()

,data_hora,setor,maquina,cod_motor,sensor,temperatura,vibração,corrente,tensao,pressao,umidade,status,cod_falha,operador,turno,consumo_kwh
0,2026-01-01 00:00:00,Teste,MQ-001,MT-0000001,IOT-0037,81.4,7.73,31.06,211.6,5.76,38.5,OK,---,Carlos Souza,Terceiro,287.61
400,2026-01-05 04:00:00,Usinagem,MQ-015,MT-0000401,IOT-0035,69.3,3.57,36.52,234.3,7.17,55.2,aprovado,NaN,João Pereira,Primeiro,225.54
401,2026-01-05 04:15:00,Bobinagem,MQ-004,MT-0000402,IOT-0029,NaN,1.71,9.87,236.5,4.01,40.2,aprovado,E101,Ricardo Silva,Madrugada,247.07
402,2026-01-05 04:30:00,Pintura,MQ-002,MT-0000403,IOT-0019,51.7,3.12,34.23,211.7,5.39,53.5,ok,E101,Camila Nunes,3,134.44
403,2026-01-05 04:45:00,Usinagem,MQ-024,MT-0000404,IOT-0018,45.7,8.57,32.04,229.8,6.85,71.6,aprovado,F012,Lucas Almeida,Segundo,208.52

In [37]:
#Status
#Padronizar para apenas:
# Aprovado
# Reprovado 
#Cria o dicionário com as regras de substituição
substituicoes = {
    #Tudo que for variação de "OK" ou "Aprovado" vira 'Aprovado'
    'OK': 'Aprovado',
    'Ok': 'Aprovado',
    'ok': 'Aprovado',
    'APROVADO': 'Aprovado',
    'aprovado': 'Aprovado',
    
    #Tudo que for variação de "Reprovado" ou "Falha" vira 'Reprovado'
    'REPROVADO': 'Reprovado',
    'Falha': 'Reprovado',
    'FALHA': 'Reprovado'
}

#Aplica as substituições na coluna 'status'
dataset['status'] = dataset['status'].replace(substituicoes)

#Contagem final
dataset['status'].value_counts()

status
Aprovado     5782
Reprovado    3819
Name: count, dtype: int64

In [44]:
#Conta tudo, com a intenção de ver os nomes
dataset['turno'].value_counts()

turno
Segundo      1435
Madrugada    1399
Primeiro     1378
3            1372
2            1359
1            1339
Terceiro     1319
Name: count, dtype: int64

In [51]:
#Turnos
#Padronizar para:
# 1º Turno
# 2º Turno
# 3º Turno

#Conta tudo, com a intenção de ver os nomes
dataset['turno'].value_counts()


turnos = {
    'Primeiro': '1º Turno',
    '1': '1º Turno',
    'Segundo': '2º Turno',
    '2': '2º Turno',
    'Terceiro': '3º Turno',
    '3': '3º Turno',
    'Madrugada': '3º Turno'
}

#Substitui os nomes para o padrão definido
dataset['turno'] = dataset['turno'].replace(turnos)

#Contagem final
dataset['turno'].value_counts()

turno
3º Turno    4090
2º Turno    2794
1º Turno    2717
Name: count, dtype: int64

In [52]:
#Código de Falha
#Substituir:
#• NULL
#• células vazias
# por:
# SEM_FALHA

# Preenche valores nulos/vazios (NaN/NULL) por 'SEM_FALHA'
dataset['cod_falha'] = dataset['cod_falha'].fillna('SEM_FALHA')

# Se no seu arquivo houver traços como '---' ou palavras vazias, substitui por 'SEM_FALHA' também
dataset['cod_falha'] = dataset['cod_falha'].replace({'---': 'SEM_FALHA', '': 'SEM_FALHA'})

# Confere o resultado
dataset['cod_falha'].value_counts()

cod_falha
SEM_FALHA    3819
E410         1035
E101          996
F099          944
F012          943
E203          938
E305          926
Name: count, dtype: int64

In [61]:
#Temperatura
#Substituir:
# valores negativos;
# valor 999;
# valores nulos.

# Cálculo da mediana com dados válidos
filtro_validos = (dataset['temperatura'] != 999) & (dataset['temperatura'] >= 0)
mediana_temperatura = dataset[filtro_validos]['temperatura'].median()
print(f"A mediana correta é: {mediana_temperatura}")

# Substituindo os negativos e o 999 por NaN
dataset.loc[(dataset['temperatura'] == 999) | (dataset['temperatura'] < 0), 'temperatura'] = np.nan

# Preenchendo todos os vazios
dataset['temperatura'] = dataset['temperatura'].fillna(mediana_temperatura)

# Resultado final:
dataset['temperatura'].value_counts()

A mediana correta é: 65.2

temperatura
65.2    558
45.1     36
61.9     35
69.4     35
47.9     34
       ...
52.2     12
45.0     12
79.2     12
76.8     10
57.9      9
Name: count, Length: 401, dtype: int64

In [64]:
#Vibração
#Substituir:
#    valores negativos e 
#    acima do limite operacional 
#    pela 
#    mediana.


# Defini aqui qual é o limite operacional de vibração da máquina
limite_operacional = 20.0

# Cálculo da mediana com dados válidos
filtro_validos = (dataset['vibracao'] <= limite_operacional) & (dataset['vibracao'] >= 0)
mediana_vibracao = dataset[filtro_validos]['vibracao'].median()
print(f"A mediana correta é: {mediana_vibracao}")

# Substituindo os valores negativos e os acima do limite por NaN (Nulos)
dataset.loc[(dataset['vibracao'] > limite_operacional) | (dataset['vibracao'] < 0), 'vibracao'] = np.nan

# Preenchendo todos com a mediana
dataset['vibracao'] = dataset['vibracao'].fillna(mediana_vibracao)

# Resultado final
dataset['vibracao'].describe()

A mediana correta é: 6.56

count    9601.000000
mean        6.496458
std         3.131490
min         1.000000
25%         3.850000
50%         6.560000
75%         9.150000
max        12.000000
Name: vibracao, dtype: float64

In [73]:
#Corrente
#Substituir:   
# valores iguais a zero
# pela
# mediana

#Cálculo da mediana com os valores válidos
filtro_validos = (dataset['corrente'] != 0)
mediana_corrente = dataset[filtro_validos]['corrente'].median()
print(f"A mediana correta é: {mediana_corrente}")

# Preenchendo todos com a mediana
dataset['corrente'] = dataset['corrente'].replace(0.00, mediana_corrente)

# Resultado final
dataset['corrente'].value_counts()

A mediana correta é: 26.92

corrente
26.92    103
20.90     10
44.12      9
23.80      9
30.65      9
        ...
38.11      1
30.62      1
8.82       1
41.75      1
16.26      1
Name: count, Length: 3411, dtype: int64

In [75]:
#Tensão
#Corrigir valores fora da faixa operacional.

# Definindo apenas o limite operacional
limite_operacional = 245.0

# Cálculo da mediana com dados válidos (maior ou igual a 0 E menor ou igual ao limite)
filtro_validos = (dataset['tensao'] <= limite_operacional) & (dataset['tensao'] >= 0)
mediana_tensao = dataset[filtro_validos]['tensao'].median()
print(f"A mediana correta é: {mediana_tensao}")

# Substituindo os valores negativos e os acima do limite por NaN
dataset.loc[(dataset['tensao'] > limite_operacional) | (dataset['tensao'] < 0), 'tensao'] = np.nan

# Preenchendo todos os nulos com a mediana
dataset['tensao'] = dataset['tensao'].fillna(mediana_tensao)

# Resultado final para conferência
dataset['tensao'].describe()

A mediana correta é: 214.8

count    9601.000000
mean      214.031945
std         8.401193
min       100.000000
25%       214.800000
50%       214.800000
75%       214.800000
max       220.000000
Name: tensao, dtype: float64

In [78]:
#Pressão
#Substituir valores acima do limite permitido utilizando a mediana.

# Definindo apenas o limite operacional
limite_operacional = 15.0

# Cálculo da mediana com dados válidos 
filtro_validos = (dataset['pressao'] <= limite_operacional) & (dataset['pressao'] >= 0)
mediana_pressao = dataset[filtro_validos]['pressao'].median()
print(f"A mediana correta é: {mediana_pressao}")

# Substituindo os valores negativos e os acima do limite por NaN
dataset.loc[(dataset['pressao'] > limite_operacional) | (dataset['pressao'] < 0), 'pressao'] = np.nan

# Preenchendo todos os nulos com a mediana
dataset['pressao'] = dataset['pressao'].fillna(mediana_pressao)

# Resultado final
dataset['pressao'].describe()

A mediana correta é: 5.13

count    9601.000000
mean        5.141980
std         0.971437
min         3.000000
25%         4.780000
50%         5.130000
75%         5.530000
max         7.300000
Name: pressao, dtype: float64

In [90]:
#Consumo de Energia
#Tratar valores muito elevados utilizando a mediana.

# Definindo apenas o limite operacional
limite_operacional = 250.0

# Cálculo da mediana com dados válidos 
filtro_validos = (dataset['consumo_kwh'] <= limite_operacional) & (dataset['consumo_kwh'] >= 0)
mediana_consumo_kwh = dataset[filtro_validos]['consumo_kwh'].median()
print(f"A mediana correta é: {mediana_consumo_kwh}")

# Substituindo os valores negativos e os acima do limite por NaN
dataset.loc[(dataset['consumo_kwh'] > limite_operacional) | (dataset['consumo_kwh'] < 0), 'consumo_kwh'] = np.nan

# Preenchendo todos os nulos com a mediana
dataset['consumo_kwh'] = dataset['consumo_kwh'].fillna(mediana_consumo_kwh)

# Resultado final
dataset['consumo_kwh'].describe()

A mediana correta é: 186.755

count    9601.000000
mean      169.607962
std        39.394192
min        80.000000
25%       140.690000
50%       186.755000
75%       189.310000
max       239.980000
Name: consumo_kwh, dtype: float64